### PR TITLE
Suggestion of improves on Relations popup.

### PR DESCRIPTION
**Pull request by Pedro-vk**
This change is helpful when you has relations with a lot of related entities.
For example:
image
Instead of:
image

### CODE REVIEW

**Comment by schickling** [comment]
Oh wow thanks a lot @Pedro-vk! We're actually considering re-doing this part of the dashboard at the moment. @julianbauer is already looking into it.

We'd definitely would love to merge this in in the meantime. @julianbauer what do you think? 👍

**Comment by julianbauer** [comment]
I think that's a great idea. I especially like the bold fieldNames, adds a huge amount of structure. Maybe it's even enough for the related nodes to just display it like "clusternodes (35)" to save even more space. What do you think @Pedro-vk ?

**Comment by Pedro-vk** [comment]
@julianbauer like that?

image

**Comment by Pedro-vk** [comment]
Hi! @julianbauer, what you prefer?

**Comment by julianbauer** [comment]
I like your last version very much!

**Comment by Pedro-vk** [comment]
Do you want a new PR with the changes?

**Comment by schickling** [comment]
I'm sorry, seems like while renaming the repo the PR got closed automatically. We'll apply your changes manually for now. Thanks a lot @Pedro-vk! You'll see these changes shortly!

**Pull request closed without merging**
